import { Geist, Geist_Mono } from "next/font/google";
import { AppProvider } from "./Context/AppContext";
import './app.css'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Google",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="images/favicon.ico"/>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppProvider>
        {children}
        </AppProvider>
      </body>
    </html>
  );
}
